# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ithaca sustainability' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ithaca sustainability
  pod 'Alamofire'
  pod 'SnapKit'

  target 'ithaca sustainabilityTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ithaca sustainabilityUITests' do
    # Pods for testing
  end

end
